### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by annebreene** [brownerd/uuu-kit#17]
[Enter steps to reproduce:] sorry. I have no idea. was not even using javascript at the time. was editing xml. - anne

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [uuu-kit](https://github.com/brownerd/uuu-kit) package 1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At C:\Users\anneb\.atom\packages\uuu-kit\lib\paths.js:5

TypeError: Cannot read property 'path' of undefined
    at getPackagePath (/packages/uuu-kit/lib/paths.js:5:84)
    at /packages/uuu-kit/lib/paths.js:7:28)
    at /packages/uuu-kit/lib/paths.js:14:27)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:146462)
    at /packages/uuu-kit/lib/export-object.js:3:46)
    at /packages/uuu-kit/lib/export-object.js:29:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:146462)
    at /packages/uuu-kit/lib/main.js:10:43)
    at /packages/uuu-kit/lib/main.js:125:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:1:688769)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:11:3550661)
```

### Commands

```
```

### Non-Core Packages

```
kite 0.165.0 
uuu-kit 1.0.0 
```

**Comment by gandhiShepard** [comment]
Interesting. was a simple error thrown or did it also crash Atom too?

**Comment by annebreene** [comment]
I think it might have crashed Atom. I did one of those sounds good let’s try it – with no setup or preparation. And then disabled it. But since I got the strange error message I thought I should tell you.  As usual didn’t have time to fiddle with it, it’s on my list.
Thanks
Anne

**Comment by gandhiShepard** [comment]
ok. lots of weird things to debug. I think a change to the atom api broke a function. either way it should be working fine now. let me know if you have any problems
